//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/04/2026 08:11:11
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Autoberles
{
    public partial class Berles {

        public Berles()
        {
            OnCreated();
        }

        public short id { get; set; }

        public string berlo { get; set; }

        public DateTime kezdo_datum { get; set; }

        public DateTime vege_datum { get; set; }


        public virtual Auto Auto { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
