//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/04/2026 08:51:48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;

namespace Autoberles
{

    public partial class cnAutoberles : DbContext
    {

        public cnAutoberles() :
            base()
        {
            OnCreated();
        }

        public cnAutoberles(DbContextOptions<cnAutoberles> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(GetConnectionString("csKapcsolat"));
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        private static string GetConnectionString(string connectionStringName)
        {
            var configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: true, reloadOnChange: false);
            var configuration = configurationBuilder.Build();
            return configuration.GetConnectionString(connectionStringName);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<Auto> Autok
        {
            get;
            set;
        }

        public virtual DbSet<Berles> Berlesek
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.AutoMapping(modelBuilder);
            this.CustomizeAutoMapping(modelBuilder);

            this.BerlesMapping(modelBuilder);
            this.CustomizeBerlesMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region Auto Mapping

        private void AutoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Auto>().ToTable(@"Autok");
            modelBuilder.Entity<Auto>().Property(x => x.id).HasColumnName(@"id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Auto>().Property(x => x.marka).HasColumnName(@"marka").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Auto>().Property(x => x.tipus).HasColumnName(@"tipus").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Auto>().Property(x => x.berles_dij).HasColumnName(@"berles_dij").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Auto>().HasKey(@"id");
        }

        partial void CustomizeAutoMapping(ModelBuilder modelBuilder);

        #endregion

        #region Berles Mapping

        private void BerlesMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Berles>().ToTable(@"Berlesek");
            modelBuilder.Entity<Berles>().Property(x => x.id).HasColumnName(@"id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Berles>().Property(x => x.berlo).HasColumnName(@"berlo").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Berles>().Property(x => x.kezdo_datum).HasColumnName(@"kezdo_datum").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Berles>().Property(x => x.vege_datum).HasColumnName(@"vege_datum").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Berles>().Property<short>(@"autoId").HasColumnName(@"autoId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Berles>().HasKey(@"id");
        }

        partial void CustomizeBerlesMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Auto>().HasMany(x => x.Berles).WithOne(op => op.Auto).HasForeignKey(@"autoId").IsRequired(true);

            modelBuilder.Entity<Berles>().HasOne(x => x.Auto).WithMany(op => op.Berles).HasForeignKey(@"autoId").IsRequired(true);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
